#
# sys/MAKEFILE
#
# Virtual Floppy Drive for Windows NT platform
# Kernel mode driver: makefile for Windows DDK
#
# Copyright (C) 2003-2005 Ken Kato
#

!INCLUDE $(NTMAKEENV)\makefile.def

clean:
	rd /s /q $(TARGETPATH) obj
